[package]
name = "slide-puzzle"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
macroquad = "0.4.14"
rand = { version = "0.9.2", features = ["thread_rng"] }
